### PR TITLE
Fixed issue number #18

### PR DESCRIPTION
**Pull request by yatinsharmaa12**
I have added bellman-ford algorithm in c++. i have also added its us case , reference and how to use.

### CODE REVIEW

**Comment by shrinidhihegde3** [comment]
pin your issue number (#issue number) along with screenshots

**Comment by yatinsharmaa12** [comment]
I have added issue number in title

**Comment by shrinidhihegde3** [comment]
i can see code part in pr so attach screenshots of webview

**Comment by yatinsharmaa12** [comment]
Screenshot 2024-10-01 173621
I haven't added this in app.tsx as ui is not fixed but it is looking like that

**Pull request merged**
