### PR TITLE
Added Documentation and Implementation for Blowfish Cipher (Issue #49)

### PR DESCRIPTION
**Pull request by SanskariWolf**
Addes Use Case and How to use for Blowfish Cipher Algorithm.
As per the issue, also made two fields(one for the key and other one for the message) for the input from the user to encrypt/decrypt the message.

### CODE REVIEW

**Comment by shrinidhihegde3** [comment]
can you add screenshots of the output

**Comment by SanskariWolf** [comment]
Sure, Here it is.
Snippify-Hub_ScreenShot_01
Snippify-Hub_ScreenShot_02
Snippify-Hub_ScreenShot_03
Snippify-Hub_ScreenShot_04
Snippify-Hub_ScreenShot_05
Snippify-Hub_ScreenShot_06

**Review by shrinidhihegde3 — APPROVED** [review]

**Comment by shrinidhihegde3** [comment]
Give star, share and connect me through linkdin

**Comment by shrinidhihegde3** [comment]
hey with this add Reference, space and time complexity details

**Pull request merged**
