### PR TITLE
fix: 🐛 Add Python Code snippet: List comprehension

### PR DESCRIPTION
**Pull request by yashksaini-coder**
✅ Closes: #3

This pull request introduces a new feature for showcasing list comprehensions in Python within the application. The most important changes include adding a new component for list comprehension, updating various routes to include the new feature, and modifying the dashboard to display the new card for list comprehension.

New feature addition:

* [`src/snippets/Python/Listcomprehension.tsx`](diffhunk://#diff-436bef101cc7b793e7fde9cb42b011dc757751597bcbde7a9121880837267730R1-R227): Added a new component `ListComprehension` that includes detailed Python code snippets demonstrating various ways to use list comprehension for filtering, transforming, and more complex operations.

Route updates:

* [`src/App.tsx`](diffhunk://#diff-26ad4b834941d9b19ebf9db8082bd202aaf72ea0ddea85f5a8a0cb3c729cc6f2R27): Imported the `ListComprehension` component and added a new route `/listcomprehension` to render it. [[1]](diffhunk://#diff-26ad4b834941d9b19ebf9db8082bd202aaf72ea0ddea85f5a8a0cb3c729cc6f2R27) [[2]](diffhunk://#diff-26ad4b834941d9b19ebf9db8082bd202aaf72ea0ddea85f5a8a0cb3c729cc6f2R67)

Dashboard update:

* [`src/dashboard.tsx`](diffhunk://#diff-57ea6663adc6a185d3a797c096e3bacbd9e857ba18cb37077f4ed849c751ff81R33): Added a new card for "List Comprehension" that routes to `/listcomprehension`.

*************************************************************

@shrinidhihegde3 Review this PR and add labels to it `level 2`, `hacktoberfest`, `gssoc-ext`,`hacktoberfest-accepted` to it.

### CODE REVIEW

**Comment by yashksaini-coder** [comment]
[Snappify-Hub-3.webm](https://github.com/user-attachments/assets/a04cc98d-75ec-4d32-b255-3878080f54f7)

**Review by shrinidhihegde3 — APPROVED** [review]

**Comment by shrinidhihegde3** [comment]
Give star, share and connect me through linkdin

**Comment by yashksaini-coder** [comment]
> @shrinidhihegde3 Review this PR and add labels to it `level 2`, `hacktoberfest`, `gssoc-ext`,`hacktoberfest-accepted` to it.

Can you also add labels to this PR. It will help identify it.

**Comment by Hemu21** [comment]
@shrinidhihegde3  I am one of the program mangers of gssoc-ext. Can you please add the relevant level label to this pr.

**Comment by yashksaini-coder** [comment]
@Hemu21 @shrinidhihegde3 can you add gssoc & level labels

**Comment by shrinidhihegde3** [comment]
not registered in GSOC so i wont think it will work

**Pull request merged**
