### PR TITLE
Fix: Add Contributors Profiles in README

### PR DESCRIPTION
**Pull request by yashksaini-coder**
✅ Fixes: #71 

This PR adds a automated workflow to update the contributors list in the **README** file and adds a section in the README to display the contributors. The most important changes include creating a GitHub Actions workflow and updating the README file.

Workflow automation:

* [`.github/workflow/add-contributor.yml`](diffhunk://#diff-14666b860bfe1d6e9eee683f2e027b947a5d8df9a3660e56dd062bff1a67121dR1-R25): Added a new GitHub Actions workflow to automate updating the contributors list in the README file whenever changes are pushed to the `main` branch.

README updates:

* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R77-R91): Added a section to display contributors and included a "Back to Top" button for easier navigation.

*****************************************************************************************

@shrinidhihegde3 Review this PR & add hacktoberfest labels to this PR.

### CODE REVIEW

**Review by shrinidhihegde3 — APPROVED** [review]

**Comment by yashksaini-coder** [comment]
@Hemu21 @shrinidhihegde3 can you add gssoc & level labels

**Comment by Hemu21** [comment]
> @Hemu21 @shrinidhihegde3 can you add gssoc & level labels 

@yashksaini-coder this project is not under gssoc-ext only in hacktoberfest. I hope you understand.

**Comment by yashksaini-coder** [comment]
> > @Hemu21 @shrinidhihegde3 can you add gssoc & level labels
> 
> @yashksaini-coder this project is not under gssoc-ext only in hacktoberfest. I hope you understand.

Bro you send message in another PR for adding labels as this is a gssoc-ext project 

image

**Comment by Hemu21** [comment]
@yashksaini-coder  by mistake I added it.

**Comment by yashksaini-coder** [comment]
> @yashksaini-coder by mistake I added it.

bro don't get my hopes up

**Comment by shrinidhihegde3** [comment]
@Hemu21 i have not registered this repo in GSOC so by adding label will it work?

**Comment by Hemu21** [comment]
> @Hemu21 i have not registered this repo in GSOC so by adding label will it work?
> 

No it won't count towards leaderboard

**Pull request merged**
